name: Test and build stage

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
          
      - name: Installing dependancies
        run: yarn install --frozen-lockfile
      
      - name: Testing
        run: yarn test
      
      - name: Build Storybok
        run: yarn build
